### ISSUE TITLE
[request] use multiplier to determine start health level instead of hard coding it

### ISSUE THREAD

**Issue by TobiPeterG** [SmushyTaco/Health-Levels#1]
Hey there,

I really love your mod!
I noticed that the mod hard codes the health level of the player (e.g. to 10 by default).
This is an easy solution, but may lead to problems with other mods like origins or spiceoffabrics, as they also manipulate the player's health.

For example:
Let's say I have 3 mods: origins, spiceoffabric and healthlevels.

Currently,
Healthlevels sets the starting hl to 10. Spiceoffabric then reduces it by 8. origins reduces it by 10 again.
The player is left with -8 health levels.

With these changes, healthlevels would still reduce it by 50% to 10, spiceoffabric sets the hl to 60% of that (6), and origins to 50% of this (3), so the player is left with 1.5 hearts, instead of negative hearts.

This change is especially relevant, as this change would make the loading order of the mods independant. Currently, if the other two mods are loaded before this one, the health level will again be negative.
If you also implement this change, the loading order will be completely irrelevant as 40% of 60% of 50% is the same as 60% of 50% of 40% etc.. 
This might reduce unwanted results in the player's health (e.g. for me :D )

**Comment by SmushyTaco** [comment]
The starting health can be changed in the config and I'd rather keep it the way it is, if you end up having negative health changing the starting health would be a solution. With that said this mod that heavily modifies the health system wasn't really intended to be mixed with other mods that do the same as that would obviously lead to some unintended side effects.
