### ISSUE TITLE
Game crashes when opening inventory

### ISSUE THREAD

**Issue by LightningFerix** [SmushyTaco/Health-Levels#10]
Game has never crashed and has only started to crash after downloading mod (and opening inventory).

![image](https://github.com/SmushyTaco/Health-Levels/assets/79895448/68c0493e-ab1a-4979-8902-b125493b84bb)

Crash report can be supplied if necessary.

**Comment by LightningFerix** [comment]
Crashing persists after removal of mod and config file.

**Comment by LightningFerix** [comment]
After removing the mod and config file, completely deleting the player's data on the server, and doing a fresh profile (client side Fabric) the crashing issue is gone.

**Comment by SmushyTaco** [comment]
This isn't an issue with this mod

**Comment by LightningFerix** [comment]
The crashing only happens when your mod is installed and when it is removed it stops happening and when it is added once more it happens again. How can this not be an issue with this mod?
