### ISSUE TITLE
Never worked for me+ no clear indication how to uninstall it 

### ISSUE THREAD

**Issue by Zorklis** [SmushyTaco/Health-Levels#12]
1) Despite trying out this mod a few times (two years ago, today) it never worked for me. I kill or gain xp and it still doesn't fill my health bar, it's just stuck.

2) + no clear indication how to uninstall this mod. 
the player has to die for the health bar to reset after deleting it.

**Comment by SmushyTaco** [comment]
It's not stuck, it just takes a lot of XP to level up by default, this can be changed in the config.

Mods typically don't have removal instructions either and I'm not planning on implementing any sort of support system for such a thing. If you remove a mod, the content of the mod is removed and some remnants that may remain will have to be dealt with by you.
