### ISSUE TITLE
Teleporting to the Nether made this bug in 1.21

### ISSUE THREAD

**Issue by makumaku1974** [SmushyTaco/Health-Levels#15]
![image](https://github.com/user-attachments/assets/96c5ed66-cc92-4b51-86fb-38903f708820)

**Comment by SmushyTaco** [comment]
Can't reproduce. This is caused by another mod.

**Comment by cL1cKyB** [comment]
I have this mod compatibility issue too. could you please provide your mod list? I could try to help find the troublemaker.
