### ISSUE TITLE
can't edit config files directly and have to edit via modmenu?

### ISSUE THREAD

**Issue by Swordblazer** [SmushyTaco/Health-Levels#16]
i'm in the process of adding more levels that i can get and instead of copy-and-pasting xp levels in the list directly via config, i'd have to painstakingly add each entry by hand in modmenu (which takes a lot of time)

the config files do save, but they don't show up in game and the config file gets overwritten whenever i save in modmenu

**Comment by SmushyTaco** [comment]
Dude go to the config folder.

**Comment by Swordblazer** [comment]
yes i know that i have to go into the config files, edit the files manually and then save the file. the problem is that  the modmenu version of the config doesn't care about the .json config and does whatever it wants

basically, any edits done to the physical .json file isn't read read by the modmenu version of the config, but the modmenu version of the config doesn't care save to the .json config.

**Comment by SmushyTaco** [comment]
Don't run your game when you manually edit the config file and launch it afterwards. If that still doesn't work it's either a bug with Mod Menu or you're in the config folder of a different Minecraft instance.

**Comment by Swordblazer** [comment]
well that's fairly weird as editing config of every other mod works fine, just not healthlevels

and i'm editing the config of the only instance i have that has health level installed so it's not the case

i've tried editing while game is running and editing before launch but both didn't work and of course i did save

**Comment by SmushyTaco** [comment]
Maybe it's an issue with Cloth Config? I believe if you make a mistake when manually editing the config file, that cloth config falls back to the defaults, so I think it's likely that you made a very small mistake somewhere in the json which makes mod menu show you the defaults because cloth config failed to parse your changes. Check the console logs to see if any error is shown and share your config file here.

**Comment by Swordblazer** [comment]
the problem is that the value cloth config fell back to ISN'T the defaults, it's the one i've previously saved via modmenu, and i've never seen anything related in the logs
