### ISSUE TITLE
[bug] after reloading world, the health level bar is empty

### ISSUE THREAD

**Issue by TobiPeterG** [SmushyTaco/Health-Levels#2]
hey there,

I noticed that after loading a world, the health level bar is empty, until new points are garthered. Then, it's updated and shows the correct amount again.
Can this be confirmed?

I can also add screenshots if required, but I think it's pretty straight forward to reproduce :P

**Comment by SmushyTaco** [comment]
I see what you mean, I'm currently pretty busy so I'll look into fixing this when 1.18 is released.

**Comment by SmushyTaco** [comment]
Fixed in the 1.20.1 update.
