### ISSUE TITLE
Suggestion - Too big of a tooltip

### ISSUE THREAD

**Issue by Laifsyn** [SmushyTaco/Health-Levels#5]
Add comments on the config file because something is broken on my modmenu which outputs me with this longass tooltip
![image](https://user-images.githubusercontent.com/99366187/166828441-adb75c0b-8aca-4fad-89b5-1ace8ef483b3.png)

**Comment by Laifsyn** [comment]
I found the file whichs shows the tool tip here though [Raw tooltip](https://github.com/SmushyTaco/Health-Levels/blob/b93b8312d47b222fd2dde59ea1f6580d5244264f/Health%20Levels/src/main/kotlin/com/smushytaco/health_levels/configuration_support/ModConfiguration.kt)

**Comment by SmushyTaco** [comment]
This isn't something I'll be changing, the names themselves are self explanatory anyways.
