### ISSUE TITLE
When removing the mod, my health is still not default >:C

### ISSUE THREAD

**Issue by ph4tcat** [SmushyTaco/Health-Levels#6]
When removing the mod, my health is still not default >:C

**Comment by SmushyTaco** [comment]
Out of the scope of this mod. Configure your health to what you want before removing the mod then. Support for removal isn't planned.

**Comment by ph4tcat** [comment]
That sucks. but other mods have that effect when removed, so its expected.
This fixed it, you may want to note on the mod page.
Thank you!
