### ISSUE TITLE
[BUG] Levels/XP not lost on death when using Quilt

### ISSUE THREAD

**Issue by eczy-eclipse** [SmushyTaco/Health-Levels#8]
MC v1.19.2 | Quilt v0.17.6

Mod List:
- Quilted Fabric API | v4.0.0-beta.20+0.66.0
- Fabric Language Kotlin | v1.8.6+kotlin.1.7.21
- Cloth Config | v8.2.88
- Mod Menu | v4.0.6
- Health Levels | v1.0.3

Video showing config & testing: https://youtu.be/PQAgoHXDtUM
Log from above test: [latest.log](https://github.com/SmushyTaco/Health-Levels/files/10044374/latest.log)

**Comment by eczy-eclipse** [comment]
So, I just did an additional test using Fabric instead of Quilt and it works. I'm not sure what Quilt is doing differently but the Fabric API between them is the same version. (0.66.0)

**Comment by SmushyTaco** [comment]
Hey, I don't use Quilt and I'm not going to provide support for Quilt related bugs.
